@startuml

title Functional Requirements 006 - Drag and Drop. Task move to TaskstateTab

left to right direction
'top to bottom direction

'https://plantuml.com/use-case-diagram

scale 1200 width

package Functional_Requirements {

  package 001__Start {
    SystemUser - (F001_Server_Starts)
    User - (F002_Home_Page_rendered)
    (F002_Home_Page_rendered) --> (F003_Registration)
    (F002_Home_Page_rendered) --> (F004_Password_Recovery)
    (F002_Home_Page_rendered) --> (F005_Login)
    (F005_Login) ---> (F006_Page_after_first_successful_Login)
    (F006_Page_after_first_successful_Login) -> (F007_Navigation)
    (F007_Navigation) -> (F008_Logout)

    User <|- SystemUser
  }

  package 006__Drag_and_Drop {

    package 007__Task_move_to_TaskstateTab {
      (F007_Navigation) --> (F120__Drag_and_Drop__Task_move_to_taskstate_inbox)
      (F007_Navigation) --> (F121__Drag_and_Drop__Task_move_to_taskstate_today)
      (F007_Navigation) --> (F122__Drag_and_Drop__Task_move_to_taskstate_next)
      (F007_Navigation) --> (F123__Drag_and_Drop__Task_move_to_taskstate_waiting)
      (F007_Navigation) --> (F124__Drag_and_Drop__Task_move_to_taskstate_scheduled)
      (F007_Navigation) --> (F125__Drag_and_Drop__Task_move_to_taskstate_someday)
      (F007_Navigation) --> (F126__Drag_and_Drop__Task_move_to_taskstate_focus)
      (F007_Navigation) --> (F127__Drag_and_Drop__Task_move_to_taskstate_completed)
      (F007_Navigation) --> (F128__Drag_and_Drop__Task_move_to_taskstate_trash)
    }

  }

}
@enduml
