@startuml

title Functional_Requirements - Simpleworklist Use Case Diagram

left to right direction
'top to bottom direction

'https://plantuml.com/use-case-diagram

scale 1200 width

package Functional_Requirements {

  package 001__Start {
    SystemUser - (F001_Server_Starts)
    User - (F002_Home_Page_rendered)
    (F002_Home_Page_rendered) --> (F003_Registration)
    (F002_Home_Page_rendered) --> (F004_Password_Recovery)
    (F002_Home_Page_rendered) --> (F005_Login)
    (F005_Login) ---> (F006_Page_after_first_successful_Login)
    (F006_Page_after_first_successful_Login) -> (F007_Navigation)
    (F007_Navigation) -> (F008_Logout)

    User <|- SystemUser
  }

  package 002__Show_TaskstateTab {
    (F007_Navigation) --> (F010__show_taskstate_inbox)
    (F007_Navigation) --> (F011__show_taskstate_today)
    (F007_Navigation) --> (F012__show_taskstate_next)
    (F007_Navigation) --> (F013__show_taskstate_waiting)
    (F007_Navigation) --> (F014__show_taskstate_scheduled)
    (F007_Navigation) --> (F015__show_taskstate_someday)
    (F007_Navigation) --> (F016__show_taskstate_focus)
    (F007_Navigation) --> (F017__show_taskstate_completed)
    (F007_Navigation) --> (F018__show_taskstate_trash)
  }

}
@enduml
