dist: bionic
language: java
jdk: openjdk13
services:
  - docker
env:
  - COMPOSE_FILE=docker-compose.yml:docker-compose.override.travis.yml
script:
  - ./mvnw -e -DskipTests=true -B -V dependency:purge-local-repository
  - ./mvnw -e -DskipTests=true -B -V clean
  - ./mvnw -e -DskipTests=true -B -V dependency:resolve dependency:resolve-plugins dependency:sources
  - ./mvnw -e -DskipTests=true -B -V dependency:tree
  - # ./mvnw -e -DskipTests=true -B -V docker-compose:up
  - # docker ps
  - ./mvnw -e -DskipTests=true -B -V clean package spring-boot:repackage
  - ./mvnw -e -DskipTests=true -B -V site
  - # ./mvnw docker-compose:down
  - # docker ps
notifications:
  email:
    - thomas.woehlke@gmail.com
