# Use postgres/example user/password credentials
version: '3.3'

services:

  db:
    image: postgres:11.6
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: simpleworklist
      POSTGRES_PASSWORD: simpleworklistpwd
      POSTGRES_DB: simpleworklist
      CHARSET: UTF8
      PGPORT: 5433

  adminer:
    image: adminer:4.7.4
    restart: always
    ports:
      - 4000:8080
