server:
  port: ${SIMPLEWORKLIST_PORT}
  error:
    path: /fehler
  compression:
    enabled: false
    min-response-size: 2048
  servlet:
    context-path: "/simpleworklist"
spring:
  config:
    name: simpleworklist
    liquibase:
      enabled: false
    devtools:
      livereload:
        enabled: ${SIMPLEWORKLIST_DEV_TESTING}
  datasource:
    url: jdbc:postgresql://localhost:5432//simpleworklist
    username: simpleworklist
    password: simpleworklistpwd
    driverClassName: org.postgresql.Driver
    platform: postgresql
    continue-on-error: true
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: ${SIMPLEWORKLIST_JPA_DLL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
        search:
          default:
            indexBase: ~/.config/simpleworklist
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
org:
  woehlke:
    simpleworklist:
      mail:
        host: ${SIMPLEWORKLIST_MAIL_SMTP_HOST}
        port: ${SIMPLEWORKLIST_MAIL_SMTP_PORT}
        username: ${SIMPLEWORKLIST_MAIL_SMTP_USERNAME}
        password: ${SIMPLEWORKLIST_MAIL_SMTP_PASSWORD}
        auth: true
        sslEnable: true
        socketFactoryPort: 465
        socketFactoryClass: javax.net.ssl.SSLSocketFactory
      registration:
        maxRetries: 5
        ttlEmailVerificationRequest: 86400000
        urlHost: ${SIMPLEWORKLIST_URL_APP_HOST}
        mailFrom: ${SIMPLEWORKLIST_MAIL_FROM}
      webMvc:
        controllerPageSize: 10
        staticResourceHandler:
          - "/css"
          - "/img"
          - "/js"
        dynaicResourceHandler:
          - "/webjars"
      webSecurity:
        loginProcessingUrl: "/j_spring_security_check"
        logoutUrl: "/user/logout"
        cookieNamesToClear:
          - "JSESSIONID"
        invalidateHttpSession: true
        defaultSuccessUrl: "/"
        failureForwardUrl: "/user/login?login_error=1"
        usernameParameter: "j_username"
        passwordParameter: "j_password"
        loginPage: "/user/login"
        antPatternsPublic:
          - "/webjars/**"
          - "/css/**"
          - "/img/**"
          - "/js/**"
          - "/favicon.ico"
          - "/user/login*"
          - "/user/register*"
          - "/user/register/**"
          - "/user/register/confirm/**"
          - "/user/resetPassword*"
          - "/user/resetPassword/**"
          - "/user/resetPassword/confirm/**"
          - "/error*"
        strengthBCryptPasswordEncoder: 10
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simpleworklist
  profiles:
    active: default
