server:
  error:
    path: /fehler
  compression:
    enabled: true
    min-response-size: 2048
spring:
  devtools:
    livereload:
      enabled: true
  application:
    admin:
      enabled: true
  datasource:
    #url: jdbc:pgsql://localhost:5432/simpleworklist
    url: jdbc:postgresql://localhost:5432/simpleworklist
    #jdbcUrl: jdbc:postgresql://localhost:5432/simpleworklist
    username: simpleworklist
    password: simpleworklistpwd
    driverClassName: org.postgresql.Driver
    #driverClassName: com.impossibl.postgres.jdbc.PGDriver
    platform: POSTGRESQL
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: true
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
        search:
          default:
            directory_provider : filesystem
            indexBase : ${user.dir}\\simpleworklistsearch
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: ALWAYS
      cleanup-cron: 0 * * * *simpleworklist *
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      table-name: SPRING_SESSION
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
org:
  woehlke:
    simpleworklist:
      user:
        strengthBCryptPasswordEncoder: 10
      mail:
        host: sslout.df.eu
        port: 465
        username: news@thomas-woehlke.de
        password: gecgy.gKC8u3
        smtp:
          auth: true
          sslEnable: true
          socketFactoryPort: 465
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
      mvc:
        controllerPageSize: 10
      registration:
        maxRetries: 5
        ttlEmailVerificationRequest: 86400000
        urlHost: localhost:8080
        mailFrom: news@thomas-woehlke.de
---
spring:
  profiles: default
  datasource:
    url: jdbc:pgsql://localhost:5432/simpleworklist_default
---
spring:
  profiles: developing
  datasource:
    url: jdbc:pgsql://localhost:5432/simpleworklist_developing
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
---
spring:
  profiles: travis
  datasource:
    url: jdbc:pgsql://localhost:5432/simpleworklist_travis
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
server:
  compression:
    enabled: false
---
spring:
  profiles: testing
  datasource:
    url: jdbc:pgsql://localhost:5432/simpleworklist_testing
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
server:
  compression:
    enabled: false
logging:
  config: classpath:logback.xml
  file: logging-test.log
  level:
    org:
      woehlke:
          simpleworklist: DEBUG
          application: DEBUG
          config: DEBUG
          control:
            admin: DEBUG
            anonymous: DEBUG
            common: DEBUG
            user: DEBUG
          model:
            beans: DEBUG
            dao: DEBUG
            services: DEBUG
          oodm:
            entities: DEBUG
            repository: DEBUG
            services:
              impl: DEBUG
---
spring:
  profiles: qa
  datasource:
    url: jdbc:pgsql://localhost:5432/simpleworklist_qa
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
server:
  compression:
    enabled: false
logging:
  config: classpath:logback.xml
  file: logging-qa.log
  level:
    org:
      woehlke:
        simpleworklist: DEBUG
        application: DEBUG
        config: DEBUG
        control:
          admin: DEBUG
          anonymous: DEBUG
          common: DEBUG
          user: DEBUG
        model:
          beans: DEBUG
          dao: DEBUG
          services: DEBUG
        oodm:
          entities: DEBUG
          repository: DEBUG
          services:
            impl: DEBUG
---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/simpleworklist
    #url: jdbc:pgsql://localhost:5432/simpleworklist
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        search:
          default:
            indexBase : /tmp/simpleworklistsearch    
  thymeleaf:
    cache: true
  devtools:
    livereload:
      enabled: false
  application:
    admin:
      enabled: false
server:
  compression:
    enabled: true
logging:
  config: classpath:logback.xml
  #file: logging-prod.log
  level:
    org:
      woehlke:
        simpleworklist: WARN
      apache: WARN
      springframework: WARN
      thymeleaf: WARN
      hibernate: WARN
      hibernate.SQL: WARN
    ch:
      qos: WARN
