server:
  port: ${PORT}
  error:
    path: /fehler
  compression:
    enabled: false
    min-response-size: 2048
  servlet:
    context-path: "/"
spring:
  config:
    name: simpleworklist
  liquibase:
    enabled: true
  devtools:
    livereload:
      enabled: ${SIMPLEWORKLIST_DEV_TESTING}
  application:
    admin:
      enabled: ${SIMPLEWORKLIST_DEV_TESTING}
  datasource:
    url: jdbc:postgresql://${SIMPLEWORKLIST_DS_HOST}:${SIMPLEWORKLIST_DS_PORT}/${SIMPLEWORKLIST_DS_DB}
    username:  ${SIMPLEWORKLIST_DS_USR}
    password:  ${SIMPLEWORKLIST_DS_PWD}
    driverClassName: org.postgresql.Driver
  jta:
    atomikos:
      connectionfactory:
        xa-connection-factory-class-name: org.postgresql.xa.PGXAConnection
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: true
    database-platform: POSTGRESQL
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
      #ddl-auto: validate
      #ddl-auto: ${BLOODMONEY_HIBERNATE_DDL_AUTO}
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: true
        search:
          default:
            index-base: ~/.config/simpleworklist
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      platform: postgresql
      mode: ALWAYS
      continue-on-error: true
org:
  woehlke:
    java:
      simpleworklist:
        mail:
          host: ${SIMPLEWORKLIST_MAIL_SMTP_HOST}
          port: ${SIMPLEWORKLIST_MAIL_SMTP_PORT}
          username: ${SIMPLEWORKLIST_MAIL_SMTP_USERNAME}
          password: ${SIMPLEWORKLIST_MAIL_SMTP_PASSWORD}
          auth: true
          sslEnable: true
          socketFactoryPort: 465
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        registration:
          maxRetries: 5
          ttlEmailVerificationRequest: 86400000
          urlHost: ${SIMPLEWORKLIST_URL_APP_HOST}
          mailFrom: ${SIMPLEWORKLIST_MAIL_FROM}
        webMvc:
          controllerPageSize: 10
          staticResourceHandler:
            - "/favicon.ico"
            - "/css"
            - "/img"
            - "/js"
          dynamicResourceHandler:
            - "/webjars"
        webSecurity:
          strengthBCryptPasswordEncoder: 10
          # iterations: ${SIMPLEWORKLIST_USER_ITERATIONS}
          # hashWidth: ${SIMPLEWORKLIST_USER_HASH_WIDTH}
          # secret: ${SIMPLEWORKLIST_USER_SECRET}
          loginProcessingUrl: "/j_spring_security_check"
          logoutUrl: "/user/logout"
          cookieNamesToClear:
            - "JSESSIONID"
          invalidateHttpSession: true
          defaultSuccessUrl: "/"
          failureForwardUrl: "/user/logout"
          usernameParameter: "j_username"
          passwordParameter: "j_password"
          loginPage: "/user/login"
          antPatternsPublic:
            - "/favicon.ico"
            - "/favicon.ico*"
            - "/webjars/**"
            - "/css/**"
            - "/img/**"
            - "/js/**"
            - "/pages/information"
            - "/pages/information*"
            - "/pages/information/**"
            - "/pages/**"
            - "/user/login*"
            - "/user/register*"
            - "/user/register/**"
            - "/user/register/confirm/**"
            - "/user/resetPassword*"
            - "/user/resetPassword/**"
            - "/user/resetPassword/confirm/**"
            - "/error*"

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: INFO
        engine:
          internal: WARN
      ch:
        qos: WARN
      postgresql: WARN
      woehlke:
        java:
          simpleworklist: INFO
debug: false
---
spring:
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/simpleworklist
  jta:
    atomikos:
      properties:
        transaction-manager-unique-name: tx-manager-simpleworklist
    transaction-manager-id: tx-manager-simpleworklist
    log-dir: transaction-logs/tx-logs-simpleworklist
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
      #ddl-auto: validate
server:
  port: ${PORT}
  compression:
    enabled: true
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: INFO
        engine:
          internal: WARN
      ch:
        qos: WARN
      postgresql: WARN
      woehlke:
        java:
          simpleworklist: INFO
debug: false
