INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','America','Human Nature','FolkRock','1998','ozyggen','Carl');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','American Spring','Spring.....plus','Pop','1989','see for miles','Brian');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Argerich, Martha','Pianistin','Klassik','2006','ZEIT','Various');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Armstrong, Louis','Audio Archive','Blues/ Jazz','','Tring','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Astronauts, The','Competition Coupe / Surfin´ With','SurfPop','1989','Bear','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Bach, Michael','Das Schönste Geschenk','Christmas','','Wildbach','2 x');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Bach, Michael','Frohe Weihnacht','Christmas','','Single','B. Boys');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Barenaked Ladies','Brian Wilson','Pop','','Single','Promo');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beach Boys, The','Magic Collection','Surf Pop','','ARC','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beach Boys, The','The Beach Boys','Surf Pop','1990','Starlite','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beach Boys, The','California Girls','Surf Pop','1987','Capitol','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beach Boys, The','Superhits 16','Surf Pop','1992','Dynamic','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beach Boys, The','The Beach Boys','Surf Pop','1990','Duchesse','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beach Boys, The','Wonderful World','Surf Pop','1993','Remember','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beach Boys, The','Spirit of the 60s','Surf Pop','1991','TimeLife','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beach Boys, The','Summer Dreams','Surf Pop','1990','Capitol','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beach Boys, The','California Dreamin´','Surf Pop','1998','Disky','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beach Boys, The','Look Behind','Surf Pop','1993','AAD','DCD');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beatles, The','Live at the BBC','PopRock','1994','Apple','DCD Mono');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beatles, The','Baby It´s You','PopRock','1995','Apple','4 Songs');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Beau Brummels','Autumn in Frisco','Beat','1985','Edsel','60th');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Belafonte, Harry','Harry Belafonte','Folklore','','Universe','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Berg, Alban  (Quartett)','Streicher','Klassik','2006','ZEIT','Schubert');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Berry, Chuck','Is On Top','R&R','1993','MCA','50th');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Bluegrass Tribute','Pickin´ On','Bluegrass','2004','CMH','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Blues Company','Life ´89','German Blues','1989','Inak','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Braun, Frank','Batschkapp-Blues','Folklore','','Verbatin','Single');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Bruce & Terry','The Best Of','Surf Pop','1998','Sundazed','Bruce');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Burke, Solomon','Don´t Give Up On Me','SoulPop','2002','ANTI','Brian');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Callas, Maria','Sängerin','Klassik','2006','ZEIT','Various');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Casals, Pablo','Cellist','Klassik','2006','ZEIT','Bach');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Cash, Johnny','Folsom Prison / San Quentin','Country','1995','Sony','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Cash, Johnny','The Man In Black','Country','1994','Columbia','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Cash, Johnny','The Man Comes Around','Country','2002','American','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Cash, Johnny','A Hundred Highways','Country','2002','selbst','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Chaplin, Blondie','Rock + Roll','Pop','1977','Elektra','Autogramm');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Chaplin, Blondie','Hurricane','Pop','2006','Single','Autogramm');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Charles, Ray','Greatest Hits','Blues/Soul','1999','rnm','DCD');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Clapton, Eric','Unplugged','SlowRock','1992','selbst','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Clapton, Eric','The Cream of Clapron','SlowRock','1994','Polydor','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Cole, Nat King','Nat King Cole','Swing Pop','1997','wg','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Comedian Harmonists','Größten Erfolge  Vol.1','A Capella','1998','SCC','20th / 30th');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Dale, Dick','Better Shred Than Dead','Surf','1997','RHINO','DCD');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Dastan Ensemble','Homage to Molavi','Iran','1999','Sounds True','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Day, Doris','My Heart','Pop','2011','Sony','Terry, Bruce');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Deix, Manfred','Musik aus Ameriga','Pop','1995','Arcade','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Dritte Ohr, Das','Schwarz auf Weiss','German Blues','1994','Pogo','Live');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Fabulous Thunderbirds, The','Hot Stuff','BluesRock','1992','Epic','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Fischer-Dieskau, Dietrich','Sänger','Klassik','2006','ZEIT','Schubert');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Five Live','A Capella','Pop','1993','AAD','Live');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Furtwängler, Wilhelm','Dirigent','Klassik','2006','ZEIT','Beethoven');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Gabriel, Gunter','Sohn aus dem Volk','GermanCountry','2009','Warner','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Gari, Brian','Sings Brian Wilson','Pop','2002','Cast','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Gidea Park','Live in Concert','SurfPop','2013','Baker','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Gidea Park','Sun and Surf','SurfPop','1996','Hallmark','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Graaf','Different World','Deutsch Rock','1996','ADD','Ralph');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Groovties, The','Live in Hecklingen','German Beat','2000','Special','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Guns´ N´ Roses','Appetite For Destruction','Hardrock','1987','Geffen','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Hallen, Klaus (Tanzorchester)','Beach Boys for dancing','KlassikPop','1996','Hallen','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Healey, Jeff   (Band)','Cover to Cover','BluesRock','1995','Arista','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Hole, Dave','Steel On Steel','BluesRock','1995','Provogue','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Hole, Dave','Overtime','BluesRock','1993','Provogue','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Holly, Buddy','The Best Of','R&R','1990','World Star','50th');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Honeys, The','The Honeys','Surf Pop','1992','Capitol','Brian');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Hondells, The','You´re gonna Ride with Us','SurfPop','1995','ATM','Usher, Brian');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Hopkins, Rich & Luminarios','Buried Treasures','Folk','2012','Blue Rose','Autogramm');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Iceman','Thriller','DeutschPop','2009','','Holger');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Jan & Dean','Fun Fun Fun','Surf Pop','','ARC','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Jan & Dean','Greatest Hits','Surf Pop','1989','Duchesse','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Jansons, Mariss','Dirigent','Klassik','2006','ZEIT','Schostakowitsch');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','John, Elton','Reg Strikes Back','PopRock','1988','phonogramm','Bruce, Carl');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Jon & Nightriders, The','Moving Target','SurfPop','1999','Gee-Dee','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Karaoke','Backstage','SurhPop','','Graphics','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Kathy X','Ready For Anything','Pop','2004','Cosmic','Autogramm');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Kennedy, Nigel','Geiger','Klassik','2006','ZEIT','Vivaldi');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','King´s Singers, The','Good Vibrations','A Capella','1993','Single','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','King´s Singers, The','Good Vibrations','A Capella','1992','RCA','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Knopfler, Mark','Sailing to Philadelphia','Pop','2000','Mercury','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Kristofferson, Kris','This Old Road','Country','2006','New West','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Lamm, Robert','In My Heard','US Pop','1999','in akustik','Carl');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Looney Tunes, The','Beyond the Dune','Surf Rock','1997','Gee-Dee','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Magic Hero','V.S. Rock People','US Pop','2012','troun','Manson');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Mavericks, The','Music for all Occasions','Country','1995','MCA','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Mavericks, The','Trampoline','Country','1998','MCA','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Memories, The','Forever Young','Pop','1996','ADD','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Memphis Slim','Harlem Bound','Swing / Blues','','','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Menuhin, Yehudi','Geiger','Klassik','2006','ZEIT','Various');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','MP    (Melting Point)','Bursting Out','Heavy Metal','1999','Shark','Autogramm');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','MP    (Melting Point)','Melting Point','Heavy Metal','1992','Savage','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Müller, Stephan','Cembalo','Klassik','','selbst','Tina');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Nazeri, Shahram','Charming Sorrow','Iran','','','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Nelson, Willie','Red Headed Stranger','Country','1975','CBS','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','New Symphonic Orchestra','The Beach Boys','KlassikPop','1999','Disky','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Niemandsland','Stunde Null','Liedermacher','2006','','Ilona');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Oasis','Definitely Maybe','BritPop','1994','Sony','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Palast Orchester, Das','Wintergarten','Swing','1993','Monopol','20th / 30th');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Papa O','Back from Space','Pop','1994','ATM','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Pfeffermond','Ondas de Som','Folklore','2008','rbb','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Pollini, Maurizio','Pianist','Klassik','2006','ZEIT','Chopin');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Presley, Elvis','Good Rockin´ Tonight','R&R','1988','Take Off','50th');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Pretty Thinks, The','Unrepentant','R&B Rock','1995','SPV','DCD');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Queen','Best of Vol.1','Hardrock','1995','Sony','Ilona');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Rämouns, The','Rockaway Beach Boys','Punkrock','2009','Wolverine','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','R.E.M.','Out Of Time','Independent','1991','Warner','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Rea, Chris','The Very Best','Rock','2001','Warner','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Revere, Paul & Raiders, The','The Essential Ride','US Beat','1995','Sony','60th');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Riemann, Torsten','Auf einmal kannst Du Fliegen','Liedermacher','1995','Rockwerk','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Rip Chords, The','Three Window Coupe','Surf Pop','1996','Sundazed','Bruce');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Rip Chords, The','Hey Little Cobra','Surf Pop','1996','Sundazed','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Roadrunners, The','The Beat Is Back','German Beat','1997','R.R. Music','60th');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Royal Philharmonic Orchestra','Music of the Beach Boys','Klassik','1998','Intersound','BeachBoys');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Sa Ba Dö','Hemmweh','Folklore','','Wildbach','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Schuhmann, Coco','50 Years in Jazz','Swing','1997','Trikont','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Schwarzkopf, Elisabeth','Sopranistin','Klassik','2006','ZEIT','Strauss');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Second Try','Fake','DeutschPop','','','Holger');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Sentinals, The','Surfer Girl / Big Surf!','Surf','1995','Repertoire','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Setzer, Brian','Tribute To SUN Records','Rockabilly','2005','Surfdog','50th');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Setzer, Brian','´68 Comeback Special','BluesRock','2001','Ignition','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Setzer, Brian Orchestra','Setzer, Brian Orchestra','SwingPop','1994','ING','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Setzer, Brian Orchestra','Dirty Boogie','Boogie','1998','Interscope','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Shonen Knife','Get the Wow','Pop','1993','Aucusi','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Sting','Brand New Day','ArtPop','1999','A6M','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Slackmates, The','Hot Car Girls','Surf Rock','1997','Gee-Dee','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Status Quo','Don´t Stop','Boogie/Rock','1996','Polygram','BeachBoys');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Strandjungs, Die','In California','Deutsch Pop','1989','Rondo','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Strandjungs, Die','Strandgold','Deutsch Pop','','Tyrolis','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Stray Cats, The','Original Cool','Rockabilly','1993','Castle','50th / 60th');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Summers, Gene','School Of R&R','R&R','','Collector','50th');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Surfgrass','Surfgrass','SurfPop','1997','','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','T – Bone','Backbone','Deutsch Rock','1999','','Ilona');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Taylor, Koko','Royal Blue','Blues/Soul','2000','Alligator','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Thomas, David & two pale boys','Surf´s Up!','ArtPop','2001','Glitterhouse','Brian');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Truck Stop','Take it easy altes Haus','GermanCountry','','Spectrum','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Turner, Tina','Good Hearded Woman','Country','1997','RockCartoon','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Usher, Gary','Add Some Music To Your Day','KlassikPop','2001','poptones','Brian');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Various  (Bach)','Best of Bach','Klassik','2003','Universal','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Vaughan, Stevie','In the Beginning','BluesRock','1980','Sony','Live');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Wilson, Carnie and Wendy','Hey Santa','Christmas','1990','SBK','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Wilsons, The','Monday Without You','SurfPop','1997','Mercury','Promo');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Wilsons, The','The Wilsons','SurfPop','1997','Mercury','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Wilson Phillips','California','Pop','2004','Columbia','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Wilson Phillips','Dedicated','Pop','2012','Masterworks','BB');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Wilson Phillips','Flesh & Blood','Pop','1992','SBK','Single');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Wilson Phillips','Give It Up','Pop','1992','SBK','Single');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Wilson Phillips','Release Me','Pop','1990','EMI','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Wilson Phillips','Shadows and Light','Pop','1992','EMI','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Wilson Phillips','You won´t me Cry','Pop','1992','SBK','Single');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Wilson Phillips','Wilson Phillips','Pop','1990','SBK','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Wondermints','Wondermints','Pop','1996','sanctuary','Brian');
INSERT INTO vinyl (rubrik,tontraeger, interpret, name, genre, jahr, label, bemerkung) VALUES ('CD','CD','Xahdja Nin','','AfroPop','','selbst','');
