# Use postgres/example user/password credentials
version: '3.3'

services:

    simpleworklist_dbmaster:
        image: postgres:latest
        restart: always
        networks:
            - net
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: simpleworklistpwd
            POSTGRES_USER: simpleworklist
            POSTGRES_DB: simpleworklist
    simpleworklist_dbref:
        image: postgres:latest
        restart: always
        networks:
            - net
        ports:
            - 5464:5432
        environment:
            POSTGRES_PASSWORD: simpleworklistrefpwd
            POSTGRES_USER: simpleworklistref
            POSTGRES_DB: simpleworklistref
    simpleworklist_adminer:
        image: adminer:latest
        restart: always
        networks:
            - net
        ports:
            - 4000:8080
networks:
    net:


