INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Anka, Paul','Diana','Classic 50 & 60','57','Highschool');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Champs, The','Too Much Tequila','Classic 50 & 60','60','Instrum.Rock');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Chaplin, B., Hart, B., Bonamassa,J.','Forever Young','Reinhold','','R & B');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Chaplin, B., Hart, B., Bonamassa,J.','Nightbush City Limit','Reinhold','','R & B');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Darin, Bobby','Mack the Knife','Classic 50 & 60','59','SwingPop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Del Vikings','Jitterbug Mary','Classic 50 & 60','57','Doo Wop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Diamonds, The','Little Darlin','Classic 50 & 60','57','Doo Wop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Diamonds, The','Words Of Love','Classic 50 & 60','57','Doo Wop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Dion','Ruby Baby','Classic 50 & 60','63','Doo Wop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Drifters, The','Down At The Club','Classic 50 & 60','60','R & B');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Exciters, The','Tell Him','Classic 50 & 60','63','Rock´n Roll');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Exciters, The','He´s Got the Power','Classic 50 & 60','63','Rock´n Roll');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Francis, Connie','Tweedle Dee','Classic 50 & 60','59','Highschool');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Hunter, Ivory Joe','Since I Met You Baby','Classic 50 & 60','56','R & B');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Lee, Brenda','I´m Sorry','Classic 50 & 60','60','CountryRock');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Little Anthony & Imperials, the','I´m Allright','Classic 50 & 60','59','Doo Wop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Little Anthony & Imperials, the','I´m Allright','Classic 50 & 60','65','Doo Wop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Little Anthony & Imperials, the','It Hurts So Bad','Classic 50 & 60','65','Doo Wop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Lymon, Franky','Goody Goody','Classic 50 & 60','57','Doo Wop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Lymon, Franky','Why Do Fools Fall In Love','Classic 50 & 60','56','Doo Wop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Niedecken, W.  Springsteen, B.','Hungry Hearts','Eckstein','','Songwriter');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Niedecken, W.  Springsteen, B.','Glory Days','Eckstein','','Songwriter');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Niedecken, W.  Springsteen, B.','Knocking On Heavens Door','Eckstein','','Songwriter');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Platters, The','Only You','Classic 50 & 60','55','Doo Wop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Platters, The','The Great Pretender','Classic 50 & 60','55','Doo Wop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Platters, The','Twilight Time','Classic 50 & 60','58','Doo Wop');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre) VALUES ('DVD','DVD','Twitty, Conway','It´s Only Make Believe','Classic 50 & 60','58','CountryRock');
