INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Amen Corner, The','Bend Me, Shape Me','Beat Club','09.03.68','Beat','29');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Amen Corner, The','Half As Nice','Beat Club','Anfang 69','','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Andrews, Chris','Pretty Belinda','Beat Club','Anfang 69','','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Andrews, Chris','To Whom It Concerns','Beat Club 2','1966','Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Andrews, Chris','Yesterday Man','Beat Club 2','1966','Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Animals, The','Knock, Knock, Knockin´','Beat Club 2','1966','R&BBeat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Animals, The','See See Rider','Beat Club 2','1966','R&BBeat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Animals, The','Shake, Rattle and Roll','Beat Club 2','1966','R&BBeat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Arnold, P.P.','First Cut Is the Deepest','Beat Club','24.06.67','Beat','21');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Association, The','Time For Living','Beat Club','22.06.68','US Vocalgroup','32');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Baldry, Long John','Let The Heartaches Begin','Beat Club','13.01.68','R&B Blues','28');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Beach Boys, The','Bluebirds Over the Mountain','Beat Club','Ende 68','','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Beach Boys, The','Break Away','Beat Club','Anfang 69','','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Beach Boys, The','California Girls','Beat Club','Anfang 69','','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Beach Boys, The','Do It Again','Beat Club','Anfang 69','','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Beach Boys, The','Surfin´ USA','Beat Club','Mitte 69','','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Bee Gees, The','Massachusetts','Beat Club','25.11.67','Beat','26');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Bee Gees, The','New York Mining Disaster','Beat Club','20.05.67','Beat','20');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Bee Gees, The','To Love Somebody','Beat Club','23.09.67','Beat','24');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Bee Gees, The','World','Beat Club','30.12.67','Beat','27');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Black Sabbath','','Beat Club 2','1970','Heavy Metal','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Blue Cher, The','Summertime Blues','Beat Club','16.11.68','Heavy Metal','37');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Bonney, Graham','Super Girl','Beat Club','28.05.66','PopBeat','8');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Bonney, Graham','Thank You Baby','Beat Club','25.02.67','PopBeat','17');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Boots, The','Gloria','Beat Club 2','22.01.66','German Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Brown, Arthur','Fire','Beat Club','31.08.68','Progr.Rock','34');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Byrds, The','Eight Miles High','Beat Club 2','1971','FolkRock','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Canned Heat','Let´s work Together','Beat Club 2','1970','BluesRock','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Canned Heat','Long Way from L.A.','Beat Club 2','1971','BluesRock','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Canned Heat','On The Road Again','Beat Club','14.09.68','BluesRock','35');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Casuals, The','Jesamine','Beat Club','12.10.68','US Beat','36');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Chicago','Transit Authority','Beat Club 2','1970','BrassRock','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Christian, Neil (Crusaders)','Two at a Time','Beat Club 2','1966','Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Cliff, Jimmy','Give A Little, Take A Little','Beat Club','22.07.67','Soul','22');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Cocker, Joe','Delta Lady','Beat Club 2','1969','SoulRock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Cocker, Joe','With a little Help from My Friend','Beat Club','Ende 68','SoulRock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Collins, Phil & Serious Band','In the Air Tonight','Knebworth  Event 1','1990','Art-Rock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Collins, Phil & Serious Band','Sussudio','Knebworth  Event 1','1990','Art-Rock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Conley, Arthur','Sweet Soul Music','Beat Club','14.09.68','Soul','35');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Cooper, Alice','Get you under my Wear','Beat Club 2','1971','Heavy Metal','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Cream, The','I Fell Free','Beat Club','25.02.67','Supergroup','17');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Cream, The','Strange Brew','Beat Club 2','1970','Supergroup','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Crease Band, The','Let it be Gone','Beat Club 2','1971','','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Creations, The','Painter Man','Beat Club','25.02.67','Beat','17');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Cupid´s Inspiration','Yesterday Has Gone','Beat Club','31.08.68','Pop','34');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Davies, Dave','Death Of A Clown','Beat Club','22.07.67','Beat','22');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Davies, Dave','Susannah´s Still Alive','Beat Club','13.01.68','Beat','28');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','David & Jonathan','Lovers Of the world United','Beat Club 2','1966','SongDuo','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Davis Group, The (Spencer)','Keep On Running','Beat Club','26.03.66','Beat','6');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Dee,Dave Dozy Peaky Mick & Tich','Hide Away','Beat Club','28.05.66','Beat','8');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Dee,Dave Dozy Peaky Mick & Tich','Hold Tight','Beat Club','28.05.66','Beat','8');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Dee,Dave Dozy Peaky Mick & Tich','Last Night In Soho','Beat Club','31.08.68','Beat','34');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Dee,Dave Dozy Peaky Mick & Tich','Legend Of Xanadoo','Beat Club','09.03.68','Beat','29');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Deep Purple','Hallelajah','Beat Club 2','1969','HardRock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Depres, Jack','Jazz Piano','Beat Club 2','1969','SwingPop','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Driscoll, Julie & Auger, Brian','This Wheels On Fire','Beat Club','22.06.68','PopChansons','32');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Easybeats, The','Friday On My Mind','Beat Club','21.12.66','Beat','15');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Easybeats, The','Good Times','Beat Club','16.11.68','Beat','37');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Easybeats, The','Lovin´ Machine','Beat Club 2','21.12.66','Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Eileen','These Boots are made for Walking','Beat Club 2','1966','Schlager','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Equals, The','Baby Come Back','Beat Club','31.08.68','Beat','34');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Equals, The','I Want Be There','Beat Club','25.02.67','Beat','17');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Fame, Georgie','Ballad Of Bonnie & Clyde','Beat Club','09.03.68','Beat','29');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Fleedwood Mac','Man Of the World','Beat Club','Anfang 69','Blues Pop','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Flower Pot Of Men','Let´s Go To San Francisco','Beat Club','25.11.67','Flower Power','26');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Gallagher, Rory','','Beat Club 2','1971','BluesRock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Garrick, David','Dear Mrs. Applebee','Beat Club 2','1966','Pop','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Gerry & Pacemaker, The','Ferry Cross the Mersey','Beat Club','04.12.65','Merseybeat','3');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Gerry & Pacemaker, The','Dizzy Miss Lizzy','Beat Club 2','1966','Merseybeat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Gibb, Robin','Save by the Bell','Beat Club','Mitte 69','','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Go Go Girls','','Beat Club','12.10.68','','36');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Hardin & York','','Beat Club 2','1970','BluesRock','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Heavens, Richie','Here Comes the Sun','Beat Club 2','1971','Pop Poet','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Heavens, Richie','Lady Madonna','Beat Club','Mitte 69','Pop Poet','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Herd, The','I Can´t Fly','Beat Club','22.07.67','Beat','22');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Herd, The','I Don´t Want Our Loving To Die','Beat Club','22.06.68','Beat','32');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Herd, The','Paradise Lost','Beat Club','13.01.68','Beat','28');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Hollies, The','I Can´t Let´s Go','Beat Club','28.05.66','Beat','8');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Hollies, The','Jennifer Ecels','Beat Club','06.09.68','Beat','30');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Hollies, The','Look Through Any Window','Beat Club','28.05.66','Beat','8');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Hollies, The','Sorry Susanne','Beat Club','Anfang 69','Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Hollies, The','This Is It','Beat Club','16.11.68','Beat','37');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Humble Pie','Natural Woman','Beat Club 2','1969','RockBlues','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Hunt, Marsha','Keep the Custumer Satisfied','Beat Club 2','1970','Soul','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Ian & Zodiacs (The)','Face In the Ground','Beat Club 2','1966','Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Ian & Zodiacs (The)','Living Long Wreck','Beat Club 2','1966','Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','King, B.B.','Heartbreaker','Beat Club','09.03.68','Gitarre','29');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Kinks, The','Mr. Plessant','Beat Club','20.05.67','Beat','20');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Kinks, The','Plastic Man','Beat Club','Anfang 69','Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Lee, Leapy','Little Arrows','Beat Club','14.09.68','Blue Eyed Soul','35');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Liverbirds, The','Bread and Butter','Beat Club 2','1966','Merseybeat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Liverbirds, The','Why don´t you hang Around','Beat Club 2','1966','Merseybeat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Lords, The','Greensleaves','Beat Club 2','28.05.66','German Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Lords, The','Poor Boy','Beat Club','28.05.66','German Beat','8');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Lords, The','Que Sera','Beat Club','22.01.66','German Beat','4');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Lords, The','Shaking All Over','Beat Club','22.01.66','German Beat','4');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Lords, The','Whishing and Hoping','Beat Club 2','22.01.66','German Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Lulu','The BoatThatI Row','Beat Club','26.06.67','UK Beat','21');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Man','','Beat Club 2','1971','Westcoast','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Mann, Manfred','Ha, Ha said the Clown','Beat Club','23.09.67','Beat','IFA Berlin  Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Mann, Manfred','Mighty Quinn','Beat Club','09.03.68','Beat','29');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Mann, Manfred','My Name Is Jack','Beat Club','22.06.68','Beat','32');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Marmelade, The','Ob La Di, Ob La Da','Beat Club','Ende 68','Pop Rock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Marquise Of Kensington','Changing Of the Guard','Beat Club','24.06.67','Orchester','21');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Mayall, John','','Beat Club 2','1970','BluesRock','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','McCartney, Paul','Birthday','Knebworth  Event 1','1990','PopRock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','McCartney, Paul','Can´t Buy Me Love','Knebworth  Event 1','1990','Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','McCartney, Paul','Coming Up','Knebworth  Event 1','1990','PopRock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','McCartney, Paul','Hey Jude','Knebworth  Event 1','1990','PopRock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','McKensey, Scott','San Francisco','Beat Club','25.11.67','Flower Power','26');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','McWilliams, David','The Days of Pearly Spencer','Beat Club','06.04.68','Beat','30');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Moody Blues, The','Nights In White Satin','Beat Club','09.03.68','Art-Rock','29');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Move, The','Fire Brigade','Beat Club','06.04.68','Beat','30');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Move, The','Wild Tiger Woman','Beat Club','14.09.68','Beat','35');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Move, The','','Beat Club 2','1971','Beat','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Mungo Jerry','In the Summertime','Beat Club 2','1970','GoodtimeRock','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Mushrooms, The','I´m Gonna Knock On Your Door','Beat Club 2','1965','Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Nice, The','America','Beat Club','14.09.68','Art-Rock','35');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Nirvana','Pentecost Hotel','Beat Club','09.03.68','Grunge','29');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Osmonds, The','Hold Her Tight','Beat Club Ende','1972','Pop','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Osmonds, The','Sweet and Annocent','Beat Club Ende','','Pop','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Osmonds, The','Too Young','Beat Club Ende','','Pop','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Osmonds, The','Why','Beat Club Ende','','Pop','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Osmonds, The','Yo Yo','Beat Club Ende','','Pop','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Passport','Uranus','Beat Club 2','1971','PopJazz','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Pitney, Gene','Something Gotta Hold Of My Heart','Beat Club','06.04.68','Pop','30');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Pitney, Gene','Somewhere In the Country','Beat Club','27.045.68','Pop','31');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Price (Set), Alan','The House that Kack build','Beat Club','23.09.67','R&B','24');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Proby, P.J.','What´s Wrong with my World','Beat Club','22.06.68','Pop Beat','32');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Procul Harum','Homburg','Beat Club','13.01.68','Art-Rock','28');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Procul Harum','Quite So Right','Beat Club','06.09.68','Art-Rock','30');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Rattles, The','Come On And Sing','Beat Club','04.12.65','German Beat','3');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Rattles, The','Little Queenie','Beat Club 2','04.12.65','German Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Remo Four, The','Like A Rolling Stone','Beat Club 2','1966','Merseybeat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Reparata & the Deirons','Captain Of Your Ship','Beat Club','27.04.68','Doo-Wop','31');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Richard, Cliff & the Shadows','Do You Wanna Dance','Knebworth  Event 1','1990','PopRock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Richard, Cliff & the Shadows','Good Golly Miss Molly','Knebworth  Event 1','1990','PopRock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Richard, Cliff & the Shadows','Living Doll','Knebworth  Event 1','1990','PopRock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Richard, Cliff & the Shadows','On the Beach','Knebworth  Event 1','1990','PopRock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Richard, Cliff & the Shadows','We Don´t Talk Anymore','Knebworth  Event 1','1990','PopRock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Rolling Stones, The','Remember Brian Jones','Beat Club','Mitte 69','','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Rose, Tim','Hey Joe','Beat Club 2','1969','Progr.Rock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Ryan, Berry','Eloise','Beat Club','16.11.68','Pop','37');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Santana (Carlos)','Black Magic Woman','Beat Club 2','1971','PercussionsSoul','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Santana (Carlos)','Jingo','Beat Club 2','1970','PercussionsSoul','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Santana (Carlos)','Jung is Red','Beat Club 2','1971','PercussionsSoul','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Sarstedt, Peter','Where Did You Go To My Lovely','Beat Club','Anfang 69','Songwriter','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Shaw, Sandy','I Don´t need that kind of Loving','Beat Club 2','1966','Pop','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Shaw, Sandy','Those Were the Day´s','Beat Club','12.10.68','Pop','36');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Slade, The','´Coz I Love You','Beat Club 2','1971','GlamRock','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Small Faces, The','Itchycoo Park','Beat Club','23.09.67','Beat','24');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Small Faces, The','Lazy Sunday','Beat Club','27.04.68','Beat','31');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Small Faces, The','Tin Soldier','Beat Club','30.12.67','Beat','27');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Sony & Cher','Little Man','Beat Club','24.09.66','BeatDuo','12');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Sony & Cher','Then He Kissed Me','Beat Club','26.08.67','BeatDuo','23');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','South, Joe','Games People Play','Beat Club','Anfang 69','Soul Pop','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Spooky Tooth, The','The Weight','Beat Club','16.11.68','Beat','37');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Status Quo, The','Ice In the Sun','Beat Club','14.09.68','RockBoogie','35');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Steppenwolf','Born To Be Wild','Beat Club','Anfang 69','German Rock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Stevens, Cat','Ain´t Gonna Get Me A Gun','Beat Club','22.07.67','Songwriter','22');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','T. Rex','','Beat Club 2','Febr. 71','GlamRock','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','T. Rex','Jeepster','Beat Club 2','1971','GlamRock','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Tandy, Sharon','Fools On the Hill','Beat Club','09.03.68','','29');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Tears For Fears','Badman´s Song','Knebworth  Event 1','1990','UK - Duo','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Tears For Fears','Change','Knebworth  Event 1','1990','UK - Duo','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Tears For Fears','Everybody Wants To Rule the World','Knebworth  Event 1','1990','UK - Duo','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Traffic','Here We Go Round The Mulberry Bush','Beat Club','09.03.68','Progr.Rock','29');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Tremeloes, The','My Little Lady','Beat Club','Anfang 69','Pop Rock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Troggs, The','Hip-Hip-Hooray','Beat Club','12.10.68','PunkRock','36');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Turner, Ike & Tina','Honky Tonk Woman','Beat Club','Febr. 71','SoulDuo','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Turner, Ike & Tina','Proud Mary','Beat Club','Febr. 71','SoulDuo','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Turner, Ike & Tina','River Deep, Mountain High','Beat Club','Febr. 71','SoulDuo','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Walker Brothers, The','Land of 1000 Dances','Beat Club','28.05.66','Beat','8');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Walker Brothers, The','Love Miking Zero','Beat Club','28.05.66','Beat','8');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Walker Brothers, The','The Sun Ain´t Gonna Shine Anymore','Beat Club','26.08.67','Beat','23');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','War Horse','','Beat Club 2','1971','Psych.Rock','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Waters, Muddy','Blowin´ the Wind my Bab´ to Me','Beat Club 2','1970','Blues','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','West, Keith','Excerpt From A Teenage Opera','Beat Club','23.09.67','Beat','24');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Winter, Johnny','Johnny B. Goode','Beat Club 2','1970','BluesRock','Farbe');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Who, The','Happy Jack','Beat Club','22.06.68','Beat','32');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Who, The','I´m A Boy','Beat Club','21.01.67','Beat','16');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Who, The','Magic Bus','Beat Club','12.10.68','Beat','36');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Who, The','Pictures Of Lily','Beat Club','20.05.67','Beat','20');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Yankees, The','La-La-La-La','Beat Club 2','25.09.65','German Beat','');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Yankees, The','Halbstark','Beat Club','25.09.65','German Beat','1');
INSERT INTO vinyl (rubrik,tontraeger, interpret, song, name, jahr, genre, bemerkung) VALUES ('VIDEO','VIDEO','Yankees, The','Tequila','Beat Club 2','26.09.65','German Beat','');
